### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by Azanty** [VerZsuT/SnowRunner-XML-Editor-Desktop#10]
Не даёт сделать - "отрицательное" значение подвески ( скидывает после того как убираешь курсор или сохраняешь. Если что - это минимальная высота ! Спасибо за отличный софт ) я тебе писал на PG но ты походу подзабил на него )

**Comment by VerZsuT** [comment]
> Не даёт сделать - "отрицательное" значение подвески ( скидывает после того как убираешь курсор или сохраняешь. Если что - это минимальная высота ! Спасибо за отличный софт ) я тебе писал на PG но ты походу подзабил на него )

Насчёт PG есть такое 😅, там даже оповещения о комментариях не приходят уже.

Как появится свободное время исправлю ошибку (примерно сегодня вечером будет патч).

**Comment by Azanty** [comment]
Параметр не критичный конечно ) Спасибо !

**Comment by VerZsuT** [comment]
Ошибка была со всеми отрицательными значениями.

Исправлено в v0.7.3b

**Comment by Azanty** [comment]
Всё обновилось ) и воркает, спасибо !
