### ISSUE TITLE
Версия 1.0.0

### ISSUE THREAD

**Issue by VerZsuT** [VerZsuT/SnowRunner-XML-Editor-Desktop#11]
### Немного истории программы.

Кому не интересно переходите к части **Вопрос**.

В самом начале (года два назад) первый прототип редактора был представлен в виде Web страницы с функционалом редактирования XML файлов игры. Но требовалось предварительно найти *initial.pak*, распаковать из него папку *[media]/classes* и после редактирования самостоятельно обновить файлы в архиве.

Так как стандартные веб технологии имеют довольно сильные ограничения, то вся версия была перенесена на десктоп с применением *Electron* и *Vue*.

Но самостоятельная работа с архивом сильно ограничивала круг пользователей (ведь некоторые не знают где находится этот зверь *initial.pak*). Вследствие чего с небольшим трудом удалось автоматизировать работу с архивом (распаковка/обновление).
Это стало поворотным моментом так как значительно увеличило колличество пользователей.

Далее проект стал увеличиваться и был переписан с *Vue* на *React* с применением *Typescript* и *Webpack*. Всё это упростило разработку и увеличило производительность.
(на этом моменте я познакомился с *Aleksvam* на *YouTube*, он сильно мне помог, за что ему отдельное спасибо 👍; он до сих пор стримит)

Следующим шагом было обновление интерфейса (все мы можем увидеть какой был интерфейс раньше просмотрев моё древнее видео на *YouTube*, p.s. кринж 😅)
Через какое-то время пришлось перейти с *MUI* на *Antd* для оптимизации интерфейса (что заняло немало времени и породило море багов, которые пришлось исправлять).

Иии... всё замерло. Обновления в игре штамповались как на принтере, а у меня всё никак не было времени (и желания, см. далее почему) на обновление программы.

*React* немного неудобен в текущее время, он имеет запары с производительностью и со своими подходами. Из-за этого (и потому что в начале его использования я мало чего в нём понимал) скопилось много "магического кода", который понять можно было только под бутылкой крепкого. В течение полугода в свободное время я переписывал весь проект в нормальный вид (а это к слову больше сотни файлов). Так вышло текущее последнее обновление.

И тут я нахожу, не побоюсь сказать, бриллиант веб разработки - *Svelte*. Он решает все мои проблемы с усложнением разработки при увеличении количества фишек в программе, имеет отличную документацию и удобное api. Это был очередной "поворотный момент".

Так как *Svelte* координально отличается от *React*, то требуется переписать всю визуальную часть программы. На ветке *migrate-to-svelte* разрабатывается следующее крупное обновление программы - *v1.0.0*. Оно исправит текущие проблемы (не баги, они исправляются на текущей версии) и добавит новые фишки, о которых вы напишете и писали ранее.

Что слелано на текущий момент:
- переход от многооконности к *single page*;
- свой *title bar* программы;
- загрузка с выводом этапов и прогресса;
- единый список вместо множества списков;
- список в виде строк (сейчас он в виде карточек);
- возможность просмотра сразу всех автомобилей в едином списке;
- фильтрация
  - **по типу файла** (авто/прицеп);
  - **по источнику** (все/dlc/мод/основное);
  - **по типу авто** (все/скаут/тяжёлый/шоссейник/вездеход);
  - **по избранному** (все/только избранное);
  - **по изменению** (все/только изменённое);
  - **по скрытию** (все/только скрытые);
 
Все фильтры могут быть применены по отдельности или одновременно.

### Вопрос

Что вы бы хотели видеть в следующем крупном обновлении (добавить/убрать/изменить)?

Известные пожелания:
- перенести доп. функционал (запчасти в аддонах, добавление прицепов/кранов) в саму таблицу;
- всевозможная фильтрация списка;
- экспорт/импорт всех изменённых файлов одной кнопкой;
- упрощение изменения полного привода до одной кнопки;
- возможность экспорта содержимого аддонов;
- возможность редактирования только выбранного авто, не затрагивая остальные (путём добавления в файл дополнительной подвески/двигателя, набора колёс и т.д., предназначенной для конкретного авто);
- описание для каждого параметра;
- параметр "затухание" у подвесок прицепов;
- возможность замены/добавления других наборов аддонов к авто (подвески/двигатели/колёса и т.д.)(колёса к прицепам);
- возможность изменения массы авто/прицепа/аддона;
- возможность ручного выбора модов не по отдельности, а целой папкой;
- параметр класса автомобиля;

**Comment by Azanty** [comment]
Хотелось-бы ) что бы прога могла редактировать вес авто (как у прицепов) у авто просто если я правильно понял несколько параметров, подвеска (шасси), кабина и может ещё редактирование веса аддонов, кранов там например, просто для осознания сколько весит машина (так сказать в сборе) и какой тяги хватит без переизбытка. Ещё было-бы прикольно, опять-же если реально это реализовать ) смену колёс у прицепов и у самих авто )) хотя я так понял что это будет (сохранение машины как сборки) но было-бы прикольно менять ещё и шины, на те что так сказать нравятся ) ещё немного про прицепы ) можно-ли им добавить параметр (как у машин) "затухание" подвески, так сказать для более тонкой настройки )

**Comment by Azanty** [comment]
Понятно, ну так и написал, если возможно, просто я моды не использую, от слова совсем и скорее всего из-за этого нет полного понимания, как это устроенно.

**Comment by L0w1y** [comment]
> * возможность редактирования только выбранного авто, не затрагивая остальные (путём добавления в файл дополнительной подвески/двигателя, набора колёс и т.д., предназначенной для конкретного авто);

Я бы хотел видеть возможность редактирования только выбранного авто, не затрагивая остальные (путём добавления в файл дополнительной подвески/двигателя, набора колёс и т.д., предназначенной для конкретного авто), а так же, чтобы программа работала с любой версией SnowRunner, хотя если вам нужно её адаптировать для каждой новой версии, то моя просьба уже звучит нелогично и нереализуемо...
