### ISSUE TITLE
Не работает с публичным тестом 25.1

### ISSUE THREAD

**Issue by L0w1y** [VerZsuT/SnowRunner-XML-Editor-Desktop#16]
Не работает с публичным тестом 25.1. Характеристики транспорта не меняются (Стокового/DLC - любого), хотя и на initial.pak он не жалуется...

**Comment by Armatores** [comment]
Надо было убрать свойство "только для чтения" с файла initial.pak

**Comment by Armatores** [comment]
А вот что действительно не работает - так это функция импорта-экспорта настроек, вернее, может она и работает, но в магазине грузовики пропадают, вместо них invalid name плашка. Вручную менять - все ок, импорт-экспорт настроек со старой версии - invalid name. А жаль, функция то реально крутая, у меня почти все грузовики модифицированные...

**Comment by VerZsuT** [comment]
Исправлено в v0.8.0
