### ISSUE TITLE
Не работает функция импорта-экспорта настроек

### ISSUE THREAD

**Issue by Armatores** [VerZsuT/SnowRunner-XML-Editor-Desktop#17]
Не работает функция импорта-экспорта настроек в бете 25.2, вернее, может она и работает, но в магазине грузовики пропадают, вместо них invalid name плашка. Вручную менять - все ок, импорт-экспорт настроек со старой версии - invalid name. А жаль, функция то реально крутая, у меня почти все грузовики модифицированные...

**Comment by VerZsuT** [comment]
Исправлено в v0.8.0
