### ISSUE TITLE
Шины

### ISSUE THREAD

**Issue by Azanty** [VerZsuT/SnowRunner-XML-Editor-Desktop#20]
Приветствую ) думал что ты уже не будешь обновлять. Очень рад что поддерживаешь, так ладно к сути ) на обнове пропали новые шины, хотя на предыдущей версии программы они были и редактировались.

**Comment by VerZsuT** [comment]
Скорее всего в их файле рутовый тег не TruckTires, а другой. В фиксе исправлю. Пока подожду, может ещё баги найдутся.

Обновление так долго выходило из-за того что мне пришлось переделать практически весь проект, ибо прошлый масштабировался с очень большими трудностями.

**Comment by VerZsuT** [comment]
Новые шины это какие именно? Чтобы я смог найти где их нет

**Comment by Azanty** [comment]
Это которые JAT они для всех машин их добавили, шины с улучшенным сцеплением типа ) да и визуал у них прикольный.

**Comment by VerZsuT** [comment]
Из новых заметил DMSH, но их программа позволяет редактировать

**Comment by VerZsuT** [comment]
Ага, в файлах нашёл, буду разбираться

**Comment by VerZsuT** [comment]
Программа раньше искала файлы только в основных папках и в папке с dlc, если это был авто из dlc, сделал чтобы всегда искало во всех dlc.
