### ISSUE TITLE
Коробка

### ISSUE THREAD

**Issue by Azanty** [VerZsuT/SnowRunner-XML-Editor-Desktop#23]
Не помню с какой версии это пошло, но на стандартной коробке меняя параметр на доступность повышенной, меняется, но в игре только понижайка доступна.

**Comment by VerZsuT** [comment]
В программе меняется атрибут **IsHighGearExists**, но в некоторых коробках не описана сама повышенная передача (**HighGear**), из-за чего она и не появляется.

**Comment by Azanty** [comment]
В более ранних версиях это срабатывало, точно помню. Да и конфиги на повышаку тоже есть, скорость и прожорливость при активации. Может они что-то поменяли.
