### ISSUE TITLE
Двигателя

### ISSUE THREAD

**Issue by Azanty** [VerZsuT/SnowRunner-XML-Editor-Desktop#28]
Не знаю у скольких это машин ) но у GMC MH9500 всего один движок ) хотя их вроде как 3 или даже 4 доступно ))

**Comment by VerZsuT** [comment]
Кхм, ошибка была даже просто в необработанном пробеле)
Вот так работало "engines1,engines2", а так "engines1, engines2" нет

**Comment by VerZsuT** [comment]
Исправил, плюс оптимизировал список авто. Вот [ссылка](https://disk.yandex.ru/d/bEP6QZhNYzi7ZQ) на портативку, выпускать в массы пока не буду, вдруг чего
