### ISSUE TITLE
Неправильные параметры отзывчивости двигателя

### ISSUE THREAD

**Issue by Armatores** [VerZsuT/SnowRunner-XML-Editor-Desktop#34]
На всех двигателях отображается параметр отзывчивости 0.04 (0.8.6), а должен быть разным, в седьмой версии все значения правильные.

**Comment by VerZsuT** [comment]
А на каком авто неправильно?
В очень большом количестве движков не указан атрибут Responsiveness, по умолчанию это 0.04, что и показывает редактор

**Comment by Armatores** [comment]
На всех автомобилях, и этот параметр обязательный, он не может быть не указан,  от него зависит насколько двигатель быстро разгоняет автомобиль, то есть набирает обороты. Значения обычно от 0.20 до 0.40 но 0.04 это вообще параметр нереалистичный. Седьмая версия показывает и меняет значения правильно на том же файле.

**Comment by VerZsuT** [comment]
Конечно я знаю что он значит)

Вот я открываю файл **[media]/classes/engines/e_ru_truck_old_heavy.xml**, в нём я вижу вот такой двигатель:
```xml
<Engine
  _template="RUTruckOldHeavyEngine"
  CriticalDamageThreshold="0.8"
  DamageCapacity="200"
  DamagedConsumptionModifier="1.6"
  FuelConsumption="6.5"
  Name="ru_truck_old_heavy_engine_0"
  Torque="160000"
  DamagedMinTorqueMultiplier="1.0"
  DamagedMaxTorqueMultiplier="0.6"
>
```
В нём нет `EngineResponsiveness`, также нет и в шаблоне **RUTruckOldHeavyEngine**
```xml
<_templates>
  <Engine>
    <RUTruckOldHeavyEngine
      BrakesDelay="0.5"
      CriticalDamageThreshold="0.7"
      DamageCapacity="200"
      DamagedMinTorqueMultiplier="1.0"
      DamagedMaxTorqueMultiplier="0.5"
      MaxDeltaAngVel="0.01"
    />
  </Engine>
</_templates>
```
Также этот атрибут не является обязательным.
![Screenshot 2024-03-05 165942](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/46576020/e84acb5d-e2e3-497d-8347-43af38bb4a29)

**initial.pak** взят из последней версии игры, не менялся, "как с завода".

Но я заметил что ошибся в названии атрибута (не `Responsiveness`, а `EngineResponsiveness`), это исправлю.
