### ISSUE TITLE
No advanced mode

### ISSUE THREAD

**Issue by Sail0609** [VerZsuT/SnowRunner-XML-Editor-Desktop#39]
I'm not sure if there is something wrong with the program or if I'm doing it the wrong way.
![1](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/143257293/dc96cd81-e84e-4110-b9f8-a3f037a14a3e)
![2](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/143257293/2c221981-fcf2-4861-b9a6-0b956477ef2f)

**Comment by VerZsuT** [comment]
This functionality is currently under development and will be released in the near future

**Comment by Sail0609** [comment]
> 此功能目前正在开发中，并将在不久的将来发布

Okay, thanks for the reply.
