### ISSUE TITLE
泰嘉6455B设置问题

### ISSUE THREAD

**Issue by jzjdcode** [VerZsuT/SnowRunner-XML-Editor-Desktop#41]
泰嘉6455B设置问题
1.悬架-差速器锁设置为已安装，游戏内差速器锁消失
2.变速箱-高速-微调设置为可用，但游戏内不可用
3.变速箱-高速-附加挡位低速+-设置为可用，但游戏内不可用

**Comment by jzjdcode** [comment]
另外一个问题，当我手动修改车辆的xml文件后（比如修改轮胎的数据），编辑器查看该车的档案似乎没有更新到最新的文件，重启编辑器后亦然

**Comment by jzjdcode** [comment]
同一个模组（Tayga 6455B Wolverine）手动打开车辆的xml文件和编辑器打开的xml文件不一致，导致出现一个问题是 我首先手动修改这个轮胎的数值0.66，之后编辑器打开该车的档案数据还是之前的0.68，这时如果编辑器点击保存，旧数据0.68就会覆盖先前修改的0.66，尝试重启编辑器后亦然
1.先手动打开车辆的xml，修改轮胎scale数据为0.66后保存
![{F739C2EA-76C2-42a4-BAB0-E73D6DE1810C}](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/50004129/8372051b-1ada-406b-8f02-058c4e585673)
2.之后通过编辑器打开档案发现scale数据还是旧数据0.68
![{651CF750-4FD3-437c-9B27-58570529A842}](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/50004129/9f202504-e65c-43a1-944a-b932f8632cf4)
![QQ截图20240328224643](https://github.com/VerZsuT/SnowRunner-XML-Editor-Desktop/assets/50004129/f0f09d31-4975-4396-9e4d-8456932e9637)

**Comment by VerZsuT** [comment]
Before any changes, the program unpacks all the necessary files to its temporary folder. If you change the file manually in the .pak file, the changes will not be reflected in the program until they are decompressed again (when the program starts).
When saved in the program, files in .pak are updated with files from the temporary folder. All manual changes can only be made in a temporary folder (which opens through the program interface), otherwise you need to restart the program before saving it.

**Comment by jzjdcode** [comment]
> Before any changes, the program unpacks all the necessary files to its temporary folder. If you change the file manually in the **.pak**, the changes will not be reflected in the program until they are unpacked again (when the program starts). When saved in the program, files in **.pak** are updated with files from the temporary folder. All manual changes can only be made in a temporary folder (which opens through the program interface), otherwise you need to restart the program before saving it.

我用我上述相同的步骤修改了rng的mb-zetros模组轮胎数据，发现编辑器重启后是可以更新数据的，但tayga这个模组则不行

**Comment by jzjdcode** [comment]
> Before any changes, the program unpacks all the necessary files to its temporary folder. If you change the file manually in the **.pak**, the changes will not be reflected in the program until they are unpacked again (when the program starts). When saved in the program, files in **.pak** are updated with files from the temporary folder. All manual changes can only be made in a temporary folder (which opens through the program interface), otherwise you need to restart the program before saving it.

懂了，感谢
