### ISSUE TITLE
Вопрос по функционалу.

### ISSUE THREAD

**Issue by Sq0Li** [VerZsuT/SnowRunner-XML-Editor-Desktop#9]
Доброго времени суток! 
Собираемся проводить турнир по SnowRunner,  в связи с чем есть вопрос:

Как правки в вашей программе работают с кооперативными сессиями? Для всех ли автомобилей применяются параметры из клиента? Или только для автомобилей клиента? Хотим постараться исключить мухлёж.

Буду очень признателен любой информации. Заранее спасибо!

**Comment by VerZsuT** [comment]
> Доброго времени суток! Собираемся проводить турнир по SnowRunner, в связи с чем есть вопрос:
> 
> Как правки в вашей программе работают с кооперативными сессиями? Для всех ли автомобилей применяются параметры из клиента? Или только для автомобилей клиента? Хотим постараться исключить мухлёж.
> 
> Буду очень признателен любой информации. Заранее спасибо!

Изменения у клиента также должны работать в кооперативе (по крайней мере раньше так было, на новых версиях не проверял). Работает только на того кто изменил, не ко всем в сессии.

Есть один несложный способ узнать есть ли изменения в игре (и предотвратить их). Для этого требуется провести проверку игры в клиенте (Steam или Epic Games). При любых найденных изменениях клиент скачает оригинальный `initial.pak` и все параметры станут стандартными.

**Comment by Azanty** [comment]
Я думаю что у вас обоих должен быть одинаковый initial.pak и проблем не будет ) но это не точно...

**Comment by VerZsuT** [comment]
> Я думаю что у вас обоих должен быть одинаковый initial.pak и проблем не будет ) но это не точно... В противном случае, будет кикать, того у кого есть изменения, если создатель сессии изменил, то думаю кикнет всех остальных, но это предположения )

Не, кикать не будет так как игре практически всё равно на файлы других людей в мультиплеере, там синхронизация по игровым событиям (едешь, доставляешь, берёшь груз и т.д.)

**Comment by Azanty** [comment]
Хммм, ей всё равно что фалы хоста и клиента отличаются ) прикольно ))) однако.

**Comment by VerZsuT** [comment]
Сам был удивлён когда по факту так и оказалось. Даже изменив кол-во топлива: ты будешь иметь 1000л в баке, а твой друг 100л, и это будет работать до тех пор пока ты не подъедешь к нему на определённое (довольно близкое) расстояние. И то даже тогда тебя не кикнет, а просто убавит топляк до стандартных 100л. Но если отъехать от друга, то снова будет 1000л.

Только разрабам известно как этот чёрный ящик работает 😆
